apiVersion: v1
kind: Service
metadata:
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    k8s-app: certificate-api
  name: certificate-api
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: "tcp-8078"
      port: 8078
      protocol: TCP
      targetPort: 8078
      nodePort: 30011
  selector:
    k8s-app: certificate-api
  sessionAffinity: None
  type: NodePort
